## Preprocessing

In [35]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
df = pd.read_csv('/Users/phunghuynh/Desktop/final project/data.csv', delimiter=';')
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Admission grade,Displaced,Educational special needs,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,International,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,5,9,127.3,1,0,0,1,1,0,20,0,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,3,3,142.5,1,0,0,0,1,0,19,0,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,9,9,124.8,1,0,0,0,1,0,19,0,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,5,3,119.6,1,0,0,1,0,0,20,0,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,9,9,141.5,0,0,0,1,0,0,45,0,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [36]:


# To display all rows
pd.set_option('display.max_rows', None)
# To display all columns
pd.set_option('display.max_columns', None)

In [37]:
df.rename(columns={"Daytime/evening attendance\t": "Attendance"}, inplace=True)
df.head()

,Marital status,Application mode,Application order,Course,Attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Admission grade,Displaced,Educational special needs,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,International,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,5,9,127.3,1,0,0,1,1,0,20,0,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,3,3,142.5,1,0,0,0,1,0,19,0,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,9,9,124.8,1,0,0,0,1,0,19,0,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,5,3,119.6,1,0,0,1,0,0,20,0,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,9,9,141.5,0,0,0,1,0,0,45,0,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [38]:
print(df['Target'].unique())

['Dropout' 'Graduate' 'Enrolled']

In [39]:
# Create a reverse mapping dictionary
mapping = {"Dropout": 0, "Graduate": 1, "Enrolled": 2}

# Replace values in the "Target" column using the mapping
df["Target"] = df["Target"].map(mapping)

# Verify the changes by printing the first few rows
print(df.head())

   Marital status  Application mode  Application order  Course  Attendance  \
0               1                17                  5     171           1
1               1                15                  1    9254           1
2               1                 1                  5    9070           1
3               1                17                  2    9773           1
4               2                39                  1    8014           0

   Previous qualification  Previous qualification (grade)  Nacionality  \
0                       1                           122.0            1
1                       1                           160.0            1
2                       1                           122.0            1
3                       1                           122.0            1
4                       1                           100.0            1

   Mother's qualification  Father's qualification  Mother's occupation  \
0                      19                      12                    5
1                       1                       3                    3
2                      37                      37                    9
3                      38                      37                    5
4                      37                      38                    9

   Father's occupation  Admission grade  Displaced  Educational special needs  \
0                    9            127.3          1                          0
1                    3            142.5          1                          0
2                    9            124.8          1                          0
3                    3            119.6          1                          0
4                    9            141.5          0                          0

   Debtor  Tuition fees up to date  Gender  Scholarship holder  \
0       0                        1       1                   0
1       0                        0       1                   0
2       0                        0       1                   0
3       0                        1       0                   0
4       0                        1       0                   0

   Age at enrollment  International  Curricular units 1st sem (credited)  \
0                 20              0                                    0
1                 19              0                                    0
2                 19              0                                    0
3                 20              0                                    0
4                 45              0                                    0

   Curricular units 1st sem (enrolled)  \
0                                    0
1                                    6
2                                    6
3                                    6
4                                    6

   Curricular units 1st sem (evaluations)  \
0                                       0
1                                       6
2                                       0
3                                       8
4                                       9

   Curricular units 1st sem (approved)  Curricular units 1st sem (grade)  \
0                                    0                          0.000000
1                                    6                         14.000000
2                                    0                          0.000000
3                                    6                         13.428571
4                                    5                         12.333333

   Curricular units 1st sem (without evaluations)  \
0                                               0
1                                               0
2                                               0
3                                               0
4                                               0

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    0
1                                    0                                    6
2                                    0                                    6
3                                    0                                    6
4                                    0                                    6

   Curricular units 2nd sem (evaluations)  \
0                                       0
1                                       6
2                                       0
3                                      10
4                                       6

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000
1                                    6                         13.666667
2                                    0                          0.000000
3                                    5                         12.400000
4                                    6                         13.000000

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8
1                                               0               13.9
2                                               0               10.8
3                                               0                9.4
4                                               0               13.9

   Inflation rate   GDP  Target
0             1.4  1.74       0
1            -0.3  0.79       1
2             1.4  1.74       0
3            -0.8 -3.12       1
4            -0.3  0.79       1

In [40]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
# application_df = application_df.drop(columns=['EIN', 'NAME'])

In [41]:
# application_df

In [42]:
# Determine the number of unique values in each column.
print(df.nunique())

Marital status                                      6
Application mode                                   18
Application order                                   8
Course                                             17
Attendance                                          2
Previous qualification                             17
Previous qualification (grade)                    101
Nacionality                                        21
Mother's qualification                             29
Father's qualification                             34
Mother's occupation                                32
Father's occupation                                46
Admission grade                                   620
Displaced                                           2
Educational special needs                           2
Debtor                                              2
Tuition fees up to date                             2
Gender                                              2
Scholarship holder                                  2
Age at enrollment                                  46
International                                       2
Curricular units 1st sem (credited)                21
Curricular units 1st sem (enrolled)                23
Curricular units 1st sem (evaluations)             35
Curricular units 1st sem (approved)                23
Curricular units 1st sem (grade)                  805
Curricular units 1st sem (without evaluations)     11
Curricular units 2nd sem (credited)                19
Curricular units 2nd sem (enrolled)                22
Curricular units 2nd sem (evaluations)             30
Curricular units 2nd sem (approved)                20
Curricular units 2nd sem (grade)                  786
Curricular units 2nd sem (without evaluations)     10
Unemployment rate                                  10
Inflation rate                                      9
GDP                                                10
Target                                              3
dtype: int64

In [43]:
# Look at Admission grade value counts to identify and replace with "Other"
# Admission_grade_counts = df['Admission grade'].value_counts()
# print(Admission_grade_counts)

In [44]:
# # Choose a cutoff value and create a list of Admission grade to be replaced
# # use the variable name `Admission_grade_to_replace`
# Admission_grade_to_replace = Admission_grade_counts[Admission_grade_counts < 8].index.tolist()

# # Replace in dataframe
# for grade in Admission_grade_to_replace:
#     df['Admission grade'] = df['Admission grade'].replace(grade,"Other")

# # Check to make sure replacement was successful
# df['Admission grade'].value_counts()

In [45]:
# Look at "Curricular units 1st sem (grade)" value counts to identify and replace with "Other"
first_sem_grade_counts = df['Curricular units 1st sem (grade)'].value_counts()
print(first_sem_grade_counts)

Curricular units 1st sem (grade)
0.000000     718
12.000000    205
13.000000    147
11.000000    138
11.500000     89
14.000000     85
12.500000     84
10.000000     82
12.666667     82
12.333333     82
11.666667     70
13.500000     63
13.333333     56
11.333333     55
10.500000     49
12.166667     46
11.250000     45
12.600000     45
11.600000     44
11.800000     43
12.200000     40
11.833333     40
12.833333     37
12.250000     37
13.666667     36
10.666667     36
11.750000     35
11.400000     35
15.000000     34
13.166667     34
12.400000     33
13.833333     33
14.500000     31
12.800000     29
13.200000     28
11.200000     24
10.800000     24
12.750000     24
13.400000     23
14.166667     23
13.600000     23
13.250000     22
14.333333     21
10.750000     21
14.200000     20
12.285714     19
13.571429     19
13.428571     19
14.666667     18
10.333333     16
12.857143     16
13.750000     15
14.833333     15
13.857143     15
13.800000     15
11.166667     15
13.285714     15
10.600000     14
16.000000     14
14.250000     13
12.571429     13
13.714286     13
11.714286     13
14.400000     12
14.428571     12
13.142857     11
12.142857     11
11.571429     10
15.166667     10
11.857143      9
11.285714      9
12.714286      8
15.500000      8
14.600000      8
10.200000      8
14.857143      8
10.833333      8
14.714286      8
10.250000      7
12.625000      7
15.200000      7
13.625000      7
13.700000      6
13.875000      6
12.428571      6
14.750000      6
15.333333      6
14.142857      6
12.375000      6
15.800000      5
13.125000      5
12.125000      5
13.375000      5
16.500000      5
15.714286      5
11.428571      5
11.875000      5
11.375000      5
14.800000      5
12.700000      5
17.000000      5
14.285714      5
11.142857      5
12.860000      4
15.571429      4
12.875000      4
15.666667      4
12.650000      4
13.442857      4
13.314286      4
15.125000      4
12.100000      4
10.571429      4
15.400000      4
13.300000      4
12.160000      4
10.400000      4
13.900000      3
14.700000      3
13.533333      3
15.285714      3
10.857143      3
13.780000      3
10.714286      3
14.850000      3
15.250000      3
14.150000      3
10.923077      3
14.350000      3
11.971429      3
11.625000      3
16.142857      3
11.916667      3
12.766667      3
10.888889      3
12.900000      3
14.060000      3
16.166667      3
13.766667      3
15.750000      3
11.555556      3
12.222222      3
14.625000      3
11.900000      3
11.888889      3
12.471429      3
14.125000      3
12.916667      3
14.757143      2
12.545455      2
14.314286      2
13.111111      2
14.014286      2
13.761111      2
12.771429      2
12.733333      2
13.976667      2
11.980000      2
13.444444      2
18.000000      2
12.357143      2
13.966667      2
13.818182      2
15.307692      2
15.833333      2
11.454545      2
12.846154      2
11.940000      2
15.692308      2
12.828571      2
13.154286      2
12.950000      2
11.545455      2
16.333333      2
12.385714      2
13.340000      2
17.333333      2
14.652857      2
13.585714      2
13.614286      2
15.428571      2
12.071429      2
14.875000      2
12.450000      2
12.887500      2
13.555556      2
14.454545      2
16.400000      2
13.846154      2
12.620000      2
14.222222      2
10.642857      2
13.683333      2
13.516667      2
13.798571      2
15.090909      2
13.385714      2
13.266667      2
15.142857      2
13.150000      2
12.320000      2
13.454545      2
13.542857      2
11.975000      2
12.153846      2
13.642857      2
12.242857      2
12.783333      2
11.950000      2
12.940000      2
12.214286      2
12.457143      2
12.485714      2
12.727273      2
14.266667      2
13.971429      2
14.727273      2
13.181818      2
13.550000      2
12.636364      2
13.785714      2
12.401429      2
12.785714      2
11.727273      2
12.555556      2
11.357143      2
10.375000      2
14.100000      2
13.075000      2
13.763750      2
12.828750      2
13.462857      2
13.416667      2
12.183333      2
14.300000      2
13.100000      2
13.457143      2
16.200000      2
14.066667      1
12.414286      1
12.444444      1
13.612500      1
14.565714      1
13.276250      1
14.375000      1
13.390000      1
12.648333      1
13.387500      1
13.958333      1
13.677143      1
14.615385      1
14.711111      1
13.755000      1
12.982857      1
12.758333      1
14.572857      1
13.422222      1
11.820000      1
13.801429      1
14.137143      1
13.670000      1
12.757143      1
10.928571      1
12.971667      1
14.636364      1
12.858000      1
14.307692      1
14.777778      1
13.272727      1
15.083333      1
12.444286      1
12.513333      1
11.155556      1
11.575000      1
13.198571      1
13.875714      1
13.153846      1
14.441429      1
13.232500      1
13.073750      1
13.464286      1
14.402500      1
15.468750      1
18.875000      1
15.885714      1
15.888889      1
12.492857      1
13.796667      1
14.962857      1
13.403750      1
11.294444      1
13.433333      1
12.742857      1
14.935714      1
12.528571      1
12.363636      1
13.058824      1
13.391667      1
15.115000      1
14.085714      1
10.166667      1
12.121429      1
14.983333      1
13.983333      1
12.692308      1
14.414286      1
14.252500      1
15.075714      1
13.778571      1
13.072857      1
16.714286      1
11.658333      1
12.560000      1
13.190000      1
11.716667      1
12.210526      1
12.461538      1
11.909091      1
13.460000      1
13.507143      1
10.368421      1
13.045000      1
13.110000      1
14.842857      1
13.046667      1
12.553750      1
12.665714      1
12.578947      1
12.002000      1
13.867143      1
12.675000      1
11.635714      1
12.526087      1
16.428571      1
13.336000      1
14.283333      1
14.115714      1
12.415000      1
14.312857      1
11.733333      1
10.900000      1
9.800000       1
15.857143      1
13.817143      1
14.208571      1
14.307143      1
11.923077      1
14.214286      1
15.077778      1
13.383333      1
13.011250      1
11.850000      1
12.327778      1
12.076923      1
11.230769      1
10.985714      1
16.131429      1
14.838571      1
13.947500      1
13.066667      1
13.746250      1
14.888750      1
14.341250      1
12.888889      1
12.365714      1
13.398000      1
11.769231      1
13.081667      1
14.594444      1
13.176471      1
12.591250      1
11.894737      1
16.833333      1
13.580000      1
11.125000      1
14.540000      1
15.675714      1
13.183333      1
11.972500      1
13.957143      1
12.910000      1
11.325000      1
15.538462      1
12.628571      1
14.057143      1
12.744286      1
13.312500      1
11.966667      1
14.950000      1
14.105714      1
14.992857      1
13.016667      1
13.327143      1
14.240000      1
11.832000      1
12.412857      1
12.545714      1
12.514286      1
13.291667      1
13.628571      1
13.736842      1
12.476190      1
13.514286      1
14.093333      1
13.557143      1
13.775714      1
13.290000      1
11.071429      1
13.861667      1
15.433333      1
15.110000      1
12.217143      1
15.798571      1
14.716667      1
13.242857      1
13.742857      1
14.368000      1
12.084286      1
13.175714      1
10.744444      1
13.417391      1
13.347500      1
13.687500      1
13.937143      1
14.538462      1
12.878571      1
12.360000      1
13.813750      1
11.962500      1
14.985714      1
13.805000      1
14.424286      1
14.110000      1
10.769231      1
14.316667      1
12.728571      1
13.681429      1
13.894286      1
13.468750      1
13.416250      1
15.300000      1
14.616667      1
12.192308      1
17.111111      1
12.841429      1
11.687500      1
12.266667      1
14.232857      1
12.350000      1
13.090909      1
15.942857      1
14.575000      1
13.470000      1
14.650000      1
14.444444      1
14.535714      1
12.506250      1
16.857143      1
15.114286      1
12.040000      1
14.328571      1
11.716667      1
12.580000      1
11.615385      1
13.995714      1
12.886250      1
14.933333      1
12.565000      1
13.060000      1
10.285714      1
12.271429      1
13.222222      1
15.101429      1
12.416667      1
14.455000      1
12.512500      1
12.328571      1
13.271429      1
12.583333      1
13.731667      1
12.412500      1
12.491667      1
10.818182      1
13.483333      1
11.642857      1
14.501250      1
11.150000      1
13.568750      1
14.153750      1
12.454286      1
13.271667      1
13.548333      1
13.257500      1
11.416667      1
11.678571      1
12.718571      1
14.485714      1
12.657143      1
13.071429      1
13.126000      1
15.052632      1
12.938750      1
12.180000      1
10.875000      1
12.687500      1
15.155556      1
13.496667      1
12.507500      1
12.090909      1
13.828571      1
12.537500      1
12.162500      1
16.885714      1
13.055556      1
12.355714      1
12.847143      1
12.340000      1
13.731250      1
13.025000      1
12.042857      1
12.837500      1
12.628571      1
11.777778      1
15.957143      1
12.228571      1
14.528571      1
14.412500      1
12.928750      1
14.402857      1
13.381429      1
14.131250      1
11.444444      1
13.310000      1
13.487143      1
11.614286      1
14.706250      1
11.814286      1
12.771250      1
11.721429      1
12.610000      1
11.690000      1
14.268750      1
15.375000      1
13.260000      1
12.414286      1
13.914286      1
13.842857      1
14.682857      1
11.461538      1
14.244444      1
12.600000      1
13.094286      1
11.705714      1
13.466667      1
14.728571      1
14.460000      1
15.228571      1
12.777778      1
13.128000      1
11.605000      1
14.016667      1
14.450000      1
12.614286      1
14.145714      1
13.362500      1
12.818182      1
13.394737      1
11.837500      1
12.684211      1
14.111111      1
13.105714      1
11.846154      1
13.471429      1
13.105000      1
13.411429      1
14.668000      1
13.345000      1
14.537143      1
13.087143      1
12.694286      1
12.300000      1
11.300000      1
13.188000      1
13.605000      1
13.863333      1
12.855556      1
14.918750      1
14.257143      1
11.683333      1
12.619048      1
13.050000      1
12.933750      1
11.816667      1
12.324286      1
12.914286      1
12.642857      1
15.625000      1
13.850000      1
17.125000      1
13.237500      1
13.814286      1
13.467143      1
13.214286      1
13.306250      1
11.437500      1
13.296667      1
12.933333      1
13.928000      1
13.044444      1
14.935000      1
13.133333      1
14.842857      1
13.080000      1
11.960000      1
14.631579      1
12.516667      1
11.616667      1
13.741667      1
12.909091      1
13.220000      1
13.151429      1
14.033333      1
13.414286      1
13.545455      1
15.135714      1
12.740000      1
11.272727      1
14.731429      1
13.615385      1
14.654286      1
11.587500      1
15.230769      1
12.901429      1
13.253750      1
13.916667      1
12.082857      1
16.153846      1
13.980000      1
12.585714      1
13.385000      1
14.828571      1
13.671429      1
12.670000      1
13.685714      1
13.797143      1
14.003750      1
14.725714      1
10.692308      1
15.116667      1
14.542857      1
13.694286      1
11.757143      1
13.058571      1
13.391250      1
12.981250      1
11.680000      1
13.175000      1
11.538462      1
13.725714      1
15.570000      1
14.114286      1
13.075714      1
13.512857      1
12.288000      1
12.765714      1
14.888889      1
13.884286      1
13.887500      1
13.427500      1
13.492857      1
14.583333      1
15.660000      1
13.557143      1
13.117143      1
12.035714      1
13.307692      1
13.053750      1
14.272727      1
12.137500      1
13.528571      1
13.637500      1
14.360000      1
14.514286      1
16.571429      1
15.145000      1
13.761250      1
15.633750      1
13.381250      1
13.342500      1
14.175000      1
14.153846      1
12.588235      1
13.435000      1
13.116667      1
13.877143      1
12.944286      1
12.993333      1
10.214286      1
11.828571      1
12.966667      1
14.125714      1
13.440000      1
13.371429      1
13.328571      1
14.377500      1
14.072222      1
12.633333      1
14.233333      1
15.700000      1
12.562500      1
13.781250      1
14.662500      1
14.141250      1
12.850000      1
12.808333      1
12.483750      1
13.450000      1
14.868571      1
13.030000      1
14.571429      1
13.367500      1
13.918571      1
13.135000      1
14.692857      1
14.035000      1
11.772500      1
12.460000      1
14.805714      1
12.725000      1
13.342857      1
12.514286      1
12.791429      1
13.058750      1
13.297143      1
13.923077      1
13.370000      1
13.485714      1
13.258571      1
13.727273      1
15.070000      1
12.606250      1
13.598333      1
12.041429      1
13.769231      1
15.444444      1
13.630000      1
16.900000      1
12.764286      1
14.071429      1
12.114286      1
11.983333      1
17.005556      1
11.994444      1
12.396667      1
15.014286      1
14.050000      1
14.787500      1
12.495714      1
14.566667      1
12.685714      1
14.445000      1
13.308571      1
14.071250      1
14.901429      1
12.135714      1
13.116250      1
14.355556      1
14.604286      1
13.576250      1
14.357143      1
13.925714      1
12.342857      1
12.908571      1
12.816667      1
11.611111      1
12.454545      1
10.983333      1
13.384615      1
16.111111      1
13.388889      1
13.583333      1
11.328571      1
13.033333      1
10.466667      1
12.835714      1
13.248750      1
13.881250      1
13.350000      1
11.421053      1
11.988571      1
11.677778      1
11.785714      1
13.423750      1
12.464286      1
13.024286      1
14.384615      1
16.461538      1
15.028571      1
14.370000      1
14.696250      1
12.855556      1
13.040000      1
15.657143      1
13.331429      1
14.912500      1
Name: count, dtype: int64

In [46]:
# # You may find it helpful to look at Curricular units 1st sem (grade) value counts >1
# first_sem_grade_counts[first_sem_grade_counts > 1]

In [47]:
# # Choose a cutoff value and create a list of "Curricular units 1st sem (grade)" to be replaced
# # use the variable name `first_sem_grade_to_replace`
# first_sem_grade_to_replace = first_sem_grade_counts[first_sem_grade_counts < 100].index.tolist()
# # Replace in dataframe
# for first_sem_grade in first_sem_grade_to_replace:
#     df['Curricular units 1st sem (grade)'] = df['Curricular units 1st sem (grade)'].replace(first_sem_grade,"Other")

# # Check to make sure replacement was successful
# df['Curricular units 1st sem (grade)'].value_counts()

In [48]:
# Convert categorical data to numeric with `pd.get_dummies`
df = pd.get_dummies(df, drop_first=True)

In [49]:
# Split our preprocessed data into our features and target arrays
y = df['Target'].values
X = df.drop(['Target'], axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [50]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [51]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train.shape[1]
hidden_nodes_layer1 = 8
hidden_nodes_layer2 = 4

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 8)              │           296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 4)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 337 (1.32 KB)

 Trainable params: 337 (1.32 KB)

 Non-trainable params: 0 (0.00 B)

In [52]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [53]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.4272 - loss: 0.8867
Epoch 2/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - accuracy: 0.6023 - loss: 0.5724
Epoch 3/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - accuracy: 0.6492 - loss: 0.3346
Epoch 4/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 506us/step - accuracy: 0.6625 - loss: 0.1330
Epoch 5/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step - accuracy: 0.6649 - loss: -0.0407
Epoch 6/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - accuracy: 0.6761 - loss: -0.1840
Epoch 7/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 518us/step - accuracy: 0.6668 - loss: -0.3290
Epoch 8/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.6804 - loss: -0.4306
Epoch 9/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 777us/step - accuracy: 0.6770 - loss: -0.6570
Epoch 10/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 537us/step - accuracy: 0.6647 - loss: -1.0107
Epoch 11/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 0.6785 - loss: -0.9526
Epoch 12/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - accuracy: 0.6705 - loss: -1.5683
Epoch 13/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 507us/step - accuracy: 0.6770 - loss: -1.7933
Epoch 14/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step - accuracy: 0.6716 - loss: -1.7985
Epoch 15/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.6907 - loss: -2.5919
Epoch 16/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.6794 - loss: -2.7458
Epoch 17/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - accuracy: 0.6797 - loss: -4.0628
Epoch 18/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.6840 - loss: -4.8199
Epoch 19/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 512us/step - accuracy: 0.7002 - loss: -5.1162
Epoch 20/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - accuracy: 0.6849 - loss: -6.7923
Epoch 21/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.6740 - loss: -8.4532
Epoch 22/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - accuracy: 0.6727 - loss: -6.3006
Epoch 23/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - accuracy: 0.6835 - loss: -11.3616
Epoch 24/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step - accuracy: 0.6844 - loss: -11.5216
Epoch 25/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step - accuracy: 0.6800 - loss: -11.4189
Epoch 26/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step - accuracy: 0.6914 - loss: -15.0590
Epoch 27/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - accuracy: 0.6955 - loss: -11.0886
Epoch 28/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - accuracy: 0.6787 - loss: -17.8279
Epoch 29/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.6764 - loss: -19.1226
Epoch 30/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - accuracy: 0.6767 - loss: -20.6419
Epoch 31/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 495us/step - accuracy: 0.6839 - loss: -18.4252
Epoch 32/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.6883 - loss: -17.1302
Epoch 33/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - accuracy: 0.6686 - loss: -21.0722
Epoch 34/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 482us/step - accuracy: 0.6839 - loss: -28.5494
Epoch 35/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - accuracy: 0.6899 - loss: -26.6499
Epoch 36/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 499us/step - accuracy: 0.6923 - loss: -32.6303
Epoch 37/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 499us/step - accuracy: 0.6794 - loss: -37.3933
Epoch 38/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 508us/step - accuracy: 0.6811 - loss: -38.7160
Epoch 39/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 508us/step - accuracy: 0.6919 - loss: -43.8360
Epoch 40/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.6839 - loss: -46.7346
Epoch 41/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 672us/step - accuracy: 0.6770 - loss: -56.2040
Epoch 42/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 526us/step - accuracy: 0.6875 - loss: -38.6886
Epoch 43/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 508us/step - accuracy: 0.6918 - loss: -66.1609
Epoch 44/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - accuracy: 0.6784 - loss: -42.6672
Epoch 45/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 508us/step - accuracy: 0.6834 - loss: -62.3296
Epoch 46/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 509us/step - accuracy: 0.6697 - loss: -49.9434
Epoch 47/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.6880 - loss: -69.0126
Epoch 48/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - accuracy: 0.6809 - loss: -67.9283
Epoch 49/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - accuracy: 0.6871 - loss: -81.4088
Epoch 50/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step - accuracy: 0.6797 - loss: -80.3149
Epoch 51/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 493us/step - accuracy: 0.6672 - loss: -84.8660
Epoch 52/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - accuracy: 0.6806 - loss: -83.1890
Epoch 53/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - accuracy: 0.6742 - loss: -92.7187
Epoch 54/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - accuracy: 0.6830 - loss: -89.5318
Epoch 55/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - accuracy: 0.6943 - loss: -73.5856
Epoch 56/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 475us/step - accuracy: 0.6880 - loss: -94.7778
Epoch 57/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 478us/step - accuracy: 0.6919 - loss: -93.3203
Epoch 58/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 592us/step - accuracy: 0.6859 - loss: -105.1750
Epoch 59/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.6777 - loss: -127.8728
Epoch 60/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 507us/step - accuracy: 0.6711 - loss: -138.0289
Epoch 61/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 0.6839 - loss: -129.1987
Epoch 62/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 495us/step - accuracy: 0.6718 - loss: -144.4903
Epoch 63/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 506us/step - accuracy: 0.6962 - loss: -114.4955
Epoch 64/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - accuracy: 0.6884 - loss: -141.5266
Epoch 65/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step - accuracy: 0.6876 - loss: -138.8012
Epoch 66/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.6915 - loss: -140.4136
Epoch 67/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.6855 - loss: -161.6363
Epoch 68/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - accuracy: 0.6678 - loss: -194.7337
Epoch 69/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step - accuracy: 0.6732 - loss: -167.8194
Epoch 70/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step - accuracy: 0.6700 - loss: -179.6971
Epoch 71/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 491us/step - accuracy: 0.6909 - loss: -179.8862
Epoch 72/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - accuracy: 0.6835 - loss: -184.3960
Epoch 73/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step - accuracy: 0.6779 - loss: -225.8116
Epoch 74/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step - accuracy: 0.6802 - loss: -196.1522
Epoch 75/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step - accuracy: 0.6718 - loss: -256.4507
Epoch 76/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 535us/step - accuracy: 0.6779 - loss: -217.4163
Epoch 77/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 511us/step - accuracy: 0.6892 - loss: -248.0422
Epoch 78/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 503us/step - accuracy: 0.6836 - loss: -257.2531
Epoch 79/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 510us/step - accuracy: 0.6789 - loss: -252.1129
Epoch 80/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.6819 - loss: -252.6856
Epoch 81/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step - accuracy: 0.6840 - loss: -292.2182
Epoch 82/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step - accuracy: 0.6773 - loss: -320.9656
Epoch 83/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 508us/step - accuracy: 0.6873 - loss: -259.7856
Epoch 84/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 513us/step - accuracy: 0.6889 - loss: -253.4459
Epoch 85/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.6765 - loss: -276.4102
Epoch 86/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 499us/step - accuracy: 0.6688 - loss: -284.4353
Epoch 87/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - accuracy: 0.6924 - loss: -318.9906
Epoch 88/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step - accuracy: 0.6870 - loss: -349.5438
Epoch 89/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 524us/step - accuracy: 0.6799 - loss: -330.4414
Epoch 90/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - accuracy: 0.6933 - loss: -343.2582
Epoch 91/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - accuracy: 0.6946 - loss: -260.3946
Epoch 92/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - accuracy: 0.6799 - loss: -404.7197
Epoch 93/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - accuracy: 0.6884 - loss: -405.4955
Epoch 94/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 502us/step - accuracy: 0.6849 - loss: -343.7135
Epoch 95/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 512us/step - accuracy: 0.6770 - loss: -392.7500
Epoch 96/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 495us/step - accuracy: 0.6798 - loss: -407.0003
Epoch 97/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - accuracy: 0.6745 - loss: -444.3187
Epoch 98/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 492us/step - accuracy: 0.6690 - loss: -459.4175
Epoch 99/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 520us/step - accuracy: 0.6910 - loss: -452.0994
Epoch 100/100
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step - accuracy: 0.6808 - loss: -387.0047

In [54]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

35/35 - 0s - 3ms/step - accuracy: 0.6899 - loss: -4.6331e+02
Loss: -463.3103332519531, Accuracy: 0.6898733973503113

In [ ]:
# Export our model to HDF5 file
nn.save(AlphabetSoupCharity.h5)