## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dropout

#  Import and read the charity_data.csv.
import pandas as pd


# To display all rows
pd.set_option('display.max_rows', None)
# To display all columns
pd.set_option('display.max_columns', None)

df = pd.read_csv('/Users/phunghuynh/Desktop/final project/data.csv', delimiter=';')
df.head()

,Marital status,Application mode,Application order,Course,Daytime/evening attendance\t,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Admission grade,Displaced,Educational special needs,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,International,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,5,9,127.3,1,0,0,1,1,0,20,0,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,3,3,142.5,1,0,0,0,1,0,19,0,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,9,9,124.8,1,0,0,0,1,0,19,0,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,5,3,119.6,1,0,0,1,0,0,20,0,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,9,9,141.5,0,0,0,1,0,0,45,0,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance	                     4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Mother's occupation                             4424 non-null   int64
 11  Father's occupation                             4424 non-null   int64
 12  Admission grade                                 4424 non-null   float64
 13  Displaced                                       4424 non-null   int64
 14  Educational special needs                       4424 non-null   int64
 15  Debtor                                          4424 non-null   int64
 16  Tuition fees up to date                         4424 non-null   int64
 17  Gender                                          4424 non-null   int64
 18  Scholarship holder                              4424 non-null   int64
 19  Age at enrollment                               4424 non-null   int64
 20  International                                   4424 non-null   int64
 21  Curricular units 1st sem (credited)             4424 non-null   int64
 22  Curricular units 1st sem (enrolled)             4424 non-null   int64
 23  Curricular units 1st sem (evaluations)          4424 non-null   int64
 24  Curricular units 1st sem (approved)             4424 non-null   int64
 25  Curricular units 1st sem (grade)                4424 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 27  Curricular units 2nd sem (credited)             4424 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 29  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 30  Curricular units 2nd sem (approved)             4424 non-null   int64
 31  Curricular units 2nd sem (grade)                4424 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 33  Unemployment rate                               4424 non-null   float64
 34  Inflation rate                                  4424 non-null   float64
 35  GDP                                             4424 non-null   float64
 36  Target                                          4424 non-null   object
dtypes: float64(7), int64(29), object(1)
memory usage: 1.2+ MB

In [3]:
df.rename(columns={"Daytime/evening attendance\t": "Attendance"}, inplace=True)
df.head()

,Marital status,Application mode,Application order,Course,Attendance,Previous qualification,Previous qualification (grade),Nacionality,Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,Admission grade,Displaced,Educational special needs,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,International,Curricular units 1st sem (credited),Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Curricular units 1st sem (without evaluations),Curricular units 2nd sem (credited),Curricular units 2nd sem (enrolled),Curricular units 2nd sem (evaluations),Curricular units 2nd sem (approved),Curricular units 2nd sem (grade),Curricular units 2nd sem (without evaluations),Unemployment rate,Inflation rate,GDP,Target
0,1,17,5,171,1,1,122.0,1,19,12,5,9,127.3,1,0,0,1,1,0,20,0,0,0,0,0,0.000000,0,0,0,0,0,0.000000,0,10.8,1.4,1.74,Dropout
1,1,15,1,9254,1,1,160.0,1,1,3,3,3,142.5,1,0,0,0,1,0,19,0,0,6,6,6,14.000000,0,0,6,6,6,13.666667,0,13.9,-0.3,0.79,Graduate
2,1,1,5,9070,1,1,122.0,1,37,37,9,9,124.8,1,0,0,0,1,0,19,0,0,6,0,0,0.000000,0,0,6,0,0,0.000000,0,10.8,1.4,1.74,Dropout
3,1,17,2,9773,1,1,122.0,1,38,37,5,3,119.6,1,0,0,1,0,0,20,0,0,6,8,6,13.428571,0,0,6,10,5,12.400000,0,9.4,-0.8,-3.12,Graduate
4,2,39,1,8014,0,1,100.0,1,37,38,9,9,141.5,0,0,0,1,0,0,45,0,0,6,9,5,12.333333,0,0,6,6,6,13.000000,0,13.9,-0.3,0.79,Graduate

In [4]:
print(df['Target'].unique())

['Dropout' 'Graduate' 'Enrolled']

In [5]:
# Create a reverse mapping dictionary
mapping = {"Dropout": 0, "Graduate": 1, "Enrolled": 2}

# Replace values in the "Target" column using the mapping
df["Target"] = df["Target"].map(mapping)

# Verify the changes by printing the first few rows
print(df.head())

   Marital status  Application mode  Application order  Course  Attendance  \
0               1                17                  5     171           1
1               1                15                  1    9254           1
2               1                 1                  5    9070           1
3               1                17                  2    9773           1
4               2                39                  1    8014           0

   Previous qualification  Previous qualification (grade)  Nacionality  \
0                       1                           122.0            1
1                       1                           160.0            1
2                       1                           122.0            1
3                       1                           122.0            1
4                       1                           100.0            1

   Mother's qualification  Father's qualification  Mother's occupation  \
0                      19                      12                    5
1                       1                       3                    3
2                      37                      37                    9
3                      38                      37                    5
4                      37                      38                    9

   Father's occupation  Admission grade  Displaced  Educational special needs  \
0                    9            127.3          1                          0
1                    3            142.5          1                          0
2                    9            124.8          1                          0
3                    3            119.6          1                          0
4                    9            141.5          0                          0

   Debtor  Tuition fees up to date  Gender  Scholarship holder  \
0       0                        1       1                   0
1       0                        0       1                   0
2       0                        0       1                   0
3       0                        1       0                   0
4       0                        1       0                   0

   Age at enrollment  International  Curricular units 1st sem (credited)  \
0                 20              0                                    0
1                 19              0                                    0
2                 19              0                                    0
3                 20              0                                    0
4                 45              0                                    0

   Curricular units 1st sem (enrolled)  \
0                                    0
1                                    6
2                                    6
3                                    6
4                                    6

   Curricular units 1st sem (evaluations)  \
0                                       0
1                                       6
2                                       0
3                                       8
4                                       9

   Curricular units 1st sem (approved)  Curricular units 1st sem (grade)  \
0                                    0                          0.000000
1                                    6                         14.000000
2                                    0                          0.000000
3                                    6                         13.428571
4                                    5                         12.333333

   Curricular units 1st sem (without evaluations)  \
0                                               0
1                                               0
2                                               0
3                                               0
4                                               0

   Curricular units 2nd sem (credited)  Curricular units 2nd sem (enrolled)  \
0                                    0                                    0
1                                    0                                    6
2                                    0                                    6
3                                    0                                    6
4                                    0                                    6

   Curricular units 2nd sem (evaluations)  \
0                                       0
1                                       6
2                                       0
3                                      10
4                                       6

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000
1                                    6                         13.666667
2                                    0                          0.000000
3                                    5                         12.400000
4                                    6                         13.000000

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8
1                                               0               13.9
2                                               0               10.8
3                                               0                9.4
4                                               0               13.9

   Inflation rate   GDP  Target
0             1.4  1.74       0
1            -0.3  0.79       1
2             1.4  1.74       0
3            -0.8 -3.12       1
4            -0.3  0.79       1

In [6]:
# Determine the number of unique values in each column.
print(df.nunique())

Marital status                                      6
Application mode                                   18
Application order                                   8
Course                                             17
Attendance                                          2
Previous qualification                             17
Previous qualification (grade)                    101
Nacionality                                        21
Mother's qualification                             29
Father's qualification                             34
Mother's occupation                                32
Father's occupation                                46
Admission grade                                   620
Displaced                                           2
Educational special needs                           2
Debtor                                              2
Tuition fees up to date                             2
Gender                                              2
Scholarship holder                                  2
Age at enrollment                                  46
International                                       2
Curricular units 1st sem (credited)                21
Curricular units 1st sem (enrolled)                23
Curricular units 1st sem (evaluations)             35
Curricular units 1st sem (approved)                23
Curricular units 1st sem (grade)                  805
Curricular units 1st sem (without evaluations)     11
Curricular units 2nd sem (credited)                19
Curricular units 2nd sem (enrolled)                22
Curricular units 2nd sem (evaluations)             30
Curricular units 2nd sem (approved)                20
Curricular units 2nd sem (grade)                  786
Curricular units 2nd sem (without evaluations)     10
Unemployment rate                                  10
Inflation rate                                      9
GDP                                                10
Target                                              3
dtype: int64

In [7]:
# Look at Admission grade value counts to identify and replace with "Other"
# Admission_grade_counts = df['Admission grade'].value_counts()
# print(Admission_grade_counts)

In [8]:
# # Choose a cutoff value and create a list of Admission grade to be replaced
# # use the variable name `Admission_grade_to_replace`
# Admission_grade_to_replace = Admission_grade_counts[Admission_grade_counts < 8].index.tolist()

# # Replace in dataframe
# for grade in Admission_grade_to_replace:
#     df['Admission grade'] = df['Admission grade'].replace(grade,"Other")

# # Check to make sure replacement was successful
# df['Admission grade'].value_counts()

In [9]:
# Look at "Curricular units 1st sem (grade)" value counts to identify and replace with "Other"
# first_sem_grade_counts = df['Curricular units 1st sem (grade)'].value_counts()
# print(first_sem_grade_counts)

In [10]:
# # look at Curricular units 1st sem (grade) value counts >1
# first_sem_grade_counts[first_sem_grade_counts > 1]

In [11]:
# # Choose a cutoff value and create a list of "Curricular units 1st sem (grade)" to be replaced
# # use the variable name `first_sem_grade_to_replace`
# first_sem_grade_to_replace = first_sem_grade_counts[first_sem_grade_counts < 100].index.tolist()
# # Replace in dataframe
# for first_sem_grade in first_sem_grade_to_replace:
#     df['Curricular units 1st sem (grade)'] = df['Curricular units 1st sem (grade)'].replace(first_sem_grade,"Other")

# # Check to make sure replacement was successful
# df['Curricular units 1st sem (grade)'].value_counts()

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
df = pd.get_dummies(df, drop_first=True)

In [13]:
# Split our preprocessed data into our features and target arrays
y = df['Target'].values
X = df.drop(['Target'], axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [20]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train.shape[1]
hidden_nodes_layer1 = 24
hidden_nodes_layer2 = 24
hidden_nodes_layer3 = 12

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='tanh'))
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='tanh'))
# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation='tanh'))
# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


# Check the structure of the model
nn.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 24)             │           888 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 24)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 24)             │           600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 24)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 12)             │           300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 12)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            13 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 1)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,801 (7.04 KB)

 Trainable params: 1,801 (7.04 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=500)

Epoch 1/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 1s 598us/step - accuracy: 0.3813 - loss: 7.8814
Epoch 2/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.4187 - loss: 7.4894
Epoch 3/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step - accuracy: 0.4064 - loss: 7.1631
Epoch 4/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 579us/step - accuracy: 0.4383 - loss: 7.5083
Epoch 5/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 566us/step - accuracy: 0.4522 - loss: 6.9034
Epoch 6/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.4146 - loss: 7.4100
Epoch 7/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.4423 - loss: 7.4890
Epoch 8/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 570us/step - accuracy: 0.4249 - loss: 7.5549
Epoch 9/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - accuracy: 0.4310 - loss: 7.2127
Epoch 10/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.4363 - loss: 6.8446
Epoch 11/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 553us/step - accuracy: 0.4470 - loss: 6.8261
Epoch 12/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.4658 - loss: 6.9337
Epoch 13/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.4313 - loss: 7.1805
Epoch 14/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - accuracy: 0.4464 - loss: 7.2827
Epoch 15/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 557us/step - accuracy: 0.4514 - loss: 6.8248
Epoch 16/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step - accuracy: 0.4588 - loss: 6.7107
Epoch 17/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.4550 - loss: 6.8256
Epoch 18/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step - accuracy: 0.4375 - loss: 7.4018
Epoch 19/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 582us/step - accuracy: 0.4492 - loss: 6.9203
Epoch 20/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 563us/step - accuracy: 0.4686 - loss: 6.8723
Epoch 21/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.4555 - loss: 7.0093
Epoch 22/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.4574 - loss: 7.0391
Epoch 23/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.4297 - loss: 7.5666
Epoch 24/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 586us/step - accuracy: 0.4566 - loss: 6.5826
Epoch 25/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step - accuracy: 0.4319 - loss: 7.8632
Epoch 26/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.4642 - loss: 6.8611
Epoch 27/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step - accuracy: 0.4552 - loss: 6.8274
Epoch 28/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 0.4682 - loss: 6.5447
Epoch 29/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - accuracy: 0.4746 - loss: 6.5830
Epoch 30/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.4869 - loss: 6.6185
Epoch 31/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 681us/step - accuracy: 0.4421 - loss: 6.6237
Epoch 32/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 591us/step - accuracy: 0.4603 - loss: 6.7281
Epoch 33/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 550us/step - accuracy: 0.4737 - loss: 6.7844
Epoch 34/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.4794 - loss: 6.8381
Epoch 35/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 570us/step - accuracy: 0.4522 - loss: 7.1535
Epoch 36/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 0.4709 - loss: 6.8988
Epoch 37/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - accuracy: 0.4877 - loss: 6.2836
Epoch 38/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 566us/step - accuracy: 0.4781 - loss: 6.6448
Epoch 39/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step - accuracy: 0.4667 - loss: 6.9681
Epoch 40/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 614us/step - accuracy: 0.4687 - loss: 6.9578
Epoch 41/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 0.4725 - loss: 7.2652
Epoch 42/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 0.4715 - loss: 6.5320
Epoch 43/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 594us/step - accuracy: 0.4705 - loss: 7.0415
Epoch 44/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.4697 - loss: 7.1115
Epoch 45/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 570us/step - accuracy: 0.4679 - loss: 6.7333
Epoch 46/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step - accuracy: 0.4925 - loss: 6.6913
Epoch 47/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - accuracy: 0.4746 - loss: 6.7892
Epoch 48/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 0.4884 - loss: 6.8100
Epoch 49/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 585us/step - accuracy: 0.4807 - loss: 7.0855
Epoch 50/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 623us/step - accuracy: 0.4679 - loss: 6.8720
Epoch 51/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step - accuracy: 0.4759 - loss: 7.2481
Epoch 52/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 596us/step - accuracy: 0.4810 - loss: 6.7857
Epoch 53/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - accuracy: 0.4773 - loss: 6.4563
Epoch 54/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - accuracy: 0.4745 - loss: 6.7998
Epoch 55/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 581us/step - accuracy: 0.4939 - loss: 6.5882
Epoch 56/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.4959 - loss: 6.5014
Epoch 57/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.4857 - loss: 6.4207
Epoch 58/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.4553 - loss: 7.3999
Epoch 59/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.4951 - loss: 6.9780
Epoch 60/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 0.4917 - loss: 7.1456
Epoch 61/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 0.4896 - loss: 6.6242
Epoch 62/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step - accuracy: 0.4688 - loss: 6.7365
Epoch 63/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 0.4865 - loss: 7.1115
Epoch 64/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - accuracy: 0.4953 - loss: 6.6411
Epoch 65/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.4863 - loss: 6.6997
Epoch 66/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step - accuracy: 0.5009 - loss: 6.4590
Epoch 67/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 542us/step - accuracy: 0.4721 - loss: 6.7801
Epoch 68/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 549us/step - accuracy: 0.5041 - loss: 6.8698
Epoch 69/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.4742 - loss: 6.9135
Epoch 70/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.4889 - loss: 6.8809
Epoch 71/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 547us/step - accuracy: 0.4859 - loss: 6.6714
Epoch 72/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.5002 - loss: 6.9906
Epoch 73/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step - accuracy: 0.4805 - loss: 6.9842
Epoch 74/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step - accuracy: 0.5013 - loss: 6.4859
Epoch 75/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - accuracy: 0.4832 - loss: 6.5546
Epoch 76/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step - accuracy: 0.5109 - loss: 6.5334
Epoch 77/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - accuracy: 0.5045 - loss: 6.6635
Epoch 78/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step - accuracy: 0.4934 - loss: 6.7166
Epoch 79/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - accuracy: 0.4719 - loss: 7.1578
Epoch 80/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step - accuracy: 0.4856 - loss: 6.4404
Epoch 81/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 573us/step - accuracy: 0.5054 - loss: 6.1350
Epoch 82/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.4999 - loss: 6.3736
Epoch 83/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 567us/step - accuracy: 0.4888 - loss: 6.6902
Epoch 84/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step - accuracy: 0.4832 - loss: 7.0267
Epoch 85/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 0.4888 - loss: 6.7482
Epoch 86/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step - accuracy: 0.4846 - loss: 6.5673
Epoch 87/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 599us/step - accuracy: 0.4862 - loss: 6.5634
Epoch 88/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 603us/step - accuracy: 0.5022 - loss: 6.6188
Epoch 89/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 597us/step - accuracy: 0.4801 - loss: 6.6780
Epoch 90/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 606us/step - accuracy: 0.4977 - loss: 6.3768
Epoch 91/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 548us/step - accuracy: 0.4749 - loss: 7.0384
Epoch 92/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 631us/step - accuracy: 0.4895 - loss: 6.9912
Epoch 93/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 642us/step - accuracy: 0.4791 - loss: 6.9029
Epoch 94/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 588us/step - accuracy: 0.5170 - loss: 6.5297
Epoch 95/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step - accuracy: 0.4928 - loss: 6.3158
Epoch 96/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 572us/step - accuracy: 0.4871 - loss: 6.7083
Epoch 97/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.5009 - loss: 6.7436
Epoch 98/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step - accuracy: 0.4892 - loss: 6.7815
Epoch 99/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 551us/step - accuracy: 0.4996 - loss: 6.6818
Epoch 100/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 568us/step - accuracy: 0.4981 - loss: 6.8191
Epoch 101/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 564us/step - accuracy: 0.4999 - loss: 7.0135
Epoch 102/500
104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 547us/step - accuracy: 0.5037 - loss: 6.2881
Epoch 103/500
  1/104 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5938 - loss: 3.0618

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

35/35 - 0s - 3ms/step - accuracy: 0.7152 - loss: -2.9632e+01
Loss: -29.6319580078125, Accuracy: 0.7151898741722107

In [19]:
# Export our model to HDF5 file
nn.save(AlphabetSoupCharity.h5)

NameError: name 'AlphabetSoupCharity' is not defined